### ISSUE TITLE
Web doesn't work with EncFS mout as a capture in docker compose

### ISSUE THREAD

**Issue by HNKNTA** [kerberos-io/web#121]
_It looks like the capture directory is missing.
Please create the directory: /etc/opt/kerberosio/capture/._

The message above appears after I open the UI using EncFS mout in docker compose.
Docker compose file:
```
version: '3.2'

services:
    machinery:
        image: kerberos/machinery
        ports:
        - "127.0.0.1:9889:8889"
        volumes:
        - capture:/etc/opt/kerberosio/capture
        - config:/etc/opt/kerberosio/config
        - logs:/etc/opt/kerberosio/logs

    web:
        image: kerberos/web
        environment:
        - KERBEROSIO_SECURE_SSL=false
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - capture:/etc/opt/kerberosio/capture
        - config:/etc/opt/kerberosio/config
        - logs:/etc/opt/kerberosio/logs
        links:
        - machinery

volumes:
    capture:
        driver_opts:
          type: none
          device: /mnt/decrypted/capture
          o: bind
    config:
    logs:
```

If I remove the capture check in _app/Http/Middleware/HasCaptureDirectory_, the UI starts as usual, it is possible to add a camera and get some video recordings done. But in the UI there is no any records. As I can see inside the containers the mount is present and accessible.

Also I've tried to run php console and make `is_directory(/etc/opt/kerberosio/capture)` and its `1`. As I can understand during the running this function returns false.
